// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AvatarMenu: typeof import('./../src/components/header/AvatarMenu.vue')['default']
    CateDist: typeof import('./../src/components/stats/CateDist.vue')['default']
    IconAkarIcons: circleCheckFill': typeof import('~icons/akar-icons/circle-check-fill')['default']
    'IconAkarIcons:circleCheckFill': typeof import('~icons/akar-icons/circle-check-fill')['default']
    IconAntDesign: loading3QuartersOutlined': typeof import('~icons/ant-design/loading3-quarters-outlined')['default']
    'IconAntDesign:loading3QuartersOutlined': typeof import('~icons/ant-design/loading3-quarters-outlined')['default']
    IconCarbonServerDns: typeof import('~icons/carbon/server-dns')['default']
    IconMdi: databaseSync': typeof import('~icons/mdi/database-sync')['default']
    'IconMdi:databaseSync': typeof import('~icons/mdi/database-sync')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NavMenu: typeof import('./../src/components/header/NavMenu.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NProgress: typeof import('naive-ui')['NProgress']
    NSelect: typeof import('naive-ui')['NSelect']
    NStatistic: typeof import('naive-ui')['NStatistic']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./../src/components/header/SearchInput.vue')['default']
  }

}
