// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AvatarMenu: typeof import('./../src/components/header/AvatarMenu.vue')['default']
    CateDist: typeof import('./../src/components/stats/CateDist.vue')['default']
    NavMenu: typeof import('./../src/components/header/NavMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./../src/components/header/SearchInput.vue')['default']
  }

}
